/*
 * JS for song55 generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '0c2b18ad-30dc-4103-ae45-9fdf77d705b4';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "song52",
    "location": "song52.html"
}, {
    "name": "songList",
    "location": "songList.html"
}, {
    "name": "song53",
    "location": "song53.html"
}, {
    "name": "song54",
    "location": "song54.html"
}, {
    "name": "song55",
    "location": "song55.html"
}, {
    "name": "song50",
    "location": "song50.html"
}, {
    "name": "song51",
    "location": "song51.html"
}];

function song55_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'html_5': 'song55_html_5'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'song55';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var song55_onLoad = function() {
        song55_elementsExtraJS();
        song55_deviceEvents();
        song55_windowEvents();
        song55_elementsEvents();
    };
    // screen window events
    function song55_windowEvents() {
        $('#song55').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function song55_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function song55_elementsExtraJS() {
        // screen (song55) extra code
    };
    // screen elements handler
    function song55_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#song55").on("pagebeforeshow", "#song55", function(event, ui) {
        Apperyio.CurrentScreen = "song55";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    song55_onLoad();
};
$(document).off("pagecreate", "#song55").on("pagecreate", "#song55", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    song55_js();
});