/*
 * JS for Song2 generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '0c2b18ad-30dc-4103-ae45-9fdf77d705b4';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Song6",
    "location": "Song6.html"
}, {
    "name": "Song7",
    "location": "Song7.html"
}, {
    "name": "Song2",
    "location": "Song2.html"
}, {
    "name": "Song8",
    "location": "Song8.html"
}, {
    "name": "BlessTheLord_1",
    "location": "BlessTheLord_1.html"
}, {
    "name": "Song9",
    "location": "Song9.html"
}, {
    "name": "Song10",
    "location": "Song10.html"
}, {
    "name": "Song3",
    "location": "Song3.html"
}, {
    "name": "startScreen_clone_1",
    "location": "startScreen_clone_1.html"
}, {
    "name": "Song4",
    "location": "Song4.html"
}, {
    "name": "Song5",
    "location": "Song5.html"
}];

function Song2_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_3': 'Song2_mobilelabel_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'Song2';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Song2_onLoad = function() {
        Song2_elementsExtraJS();
        Song2_deviceEvents();
        Song2_windowEvents();
        Song2_elementsEvents();
    };
    // screen window events
    function Song2_windowEvents() {
        $('#Song2').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Song2_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Song2_elementsExtraJS() {
        // screen (Song2) extra code
    };
    // screen elements handler
    function Song2_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#Song2").on("pagebeforeshow", "#Song2", function(event, ui) {
        Apperyio.CurrentScreen = "Song2";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Song2_onLoad();
};
$(document).off("pagecreate", "#Song2").on("pagecreate", "#Song2", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Song2_js();
});