/*
 * JS for songList generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '0c2b18ad-30dc-4103-ae45-9fdf77d705b4';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "song18",
    "location": "song18.html"
}, {
    "name": "song19",
    "location": "song19.html"
}, {
    "name": "song3",
    "location": "song3.html"
}, {
    "name": "song20",
    "location": "song20.html"
}, {
    "name": "song4",
    "location": "song4.html"
}, {
    "name": "song5",
    "location": "song5.html"
}, {
    "name": "song6",
    "location": "song6.html"
}, {
    "name": "song36",
    "location": "song36.html"
}, {
    "name": "song2",
    "location": "song2.html"
}, {
    "name": "song16",
    "location": "song16.html"
}, {
    "name": "song38",
    "location": "song38.html"
}, {
    "name": "song39",
    "location": "song39.html"
}, {
    "name": "song17",
    "location": "song17.html"
}, {
    "name": "song40",
    "location": "song40.html"
}, {
    "name": "songList",
    "location": "songList.html"
}, {
    "name": "song15",
    "location": "song15.html"
}, {
    "name": "song32",
    "location": "song32.html"
}, {
    "name": "song33",
    "location": "song33.html"
}, {
    "name": "song34",
    "location": "song34.html"
}, {
    "name": "song35",
    "location": "song35.html"
}, {
    "name": "song49",
    "location": "song49.html"
}, {
    "name": "song14",
    "location": "song14.html"
}, {
    "name": "song12",
    "location": "song12.html"
}, {
    "name": "song27",
    "location": "song27.html"
}, {
    "name": "song28",
    "location": "song28.html"
}, {
    "name": "song29",
    "location": "song29.html"
}, {
    "name": "song30",
    "location": "song30.html"
}, {
    "name": "song13",
    "location": "song13.html"
}, {
    "name": "song47",
    "location": "song47.html"
}, {
    "name": "song48",
    "location": "song48.html"
}, {
    "name": "song31",
    "location": "song31.html"
}, {
    "name": "song45",
    "location": "song45.html"
}, {
    "name": "song22",
    "location": "song22.html"
}, {
    "name": "song23",
    "location": "song23.html"
}, {
    "name": "song9",
    "location": "song9.html"
}, {
    "name": "song10",
    "location": "song10.html"
}, {
    "name": "song11",
    "location": "song11.html"
}, {
    "name": "song24",
    "location": "song24.html"
}, {
    "name": "song25",
    "location": "song25.html"
}, {
    "name": "song46",
    "location": "song46.html"
}, {
    "name": "song26",
    "location": "song26.html"
}, {
    "name": "song21",
    "location": "song21.html"
}, {
    "name": "song37",
    "location": "song37.html"
}, {
    "name": "song1",
    "location": "song1.html"
}, {
    "name": "song43",
    "location": "song43.html"
}, {
    "name": "song44",
    "location": "song44.html"
}, {
    "name": "song8",
    "location": "song8.html"
}, {
    "name": "song7",
    "location": "song7.html"
}, {
    "name": "song41",
    "location": "song41.html"
}, {
    "name": "song42",
    "location": "song42.html"
},{
    "name": "song52",
    "location": "song52.html"
}, {
    "name": "song53",
    "location": "song53.html"
}, {
    "name": "song54",
    "location": "song54.html"
}, {
    "name": "song55",
    "location": "song55.html"
}, {
    "name": "song50",
    "location": "song50.html"
}, {
    "name": "song51",
    "location": "song51.html"
}];

function songList_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'songs': 'songList_songs',
        'mobilelistitem_1': 'songList_mobilelistitem_1',
        'mobilelistitembutton_4': 'songList_mobilelistitembutton_4',
        'mobilelistitem_2': 'songList_mobilelistitem_2',
        'mobilelistitembutton_6': 'songList_mobilelistitembutton_6',
        'mobilelistitem_3': 'songList_mobilelistitem_3',
        'mobilelistitembutton_8': 'songList_mobilelistitembutton_8',
        'mobilelistitem_4': 'songList_mobilelistitem_4',
        'mobilelistitembutton_16': 'songList_mobilelistitembutton_16',
        'mobilelistitem_5': 'songList_mobilelistitem_5',
        'mobilelistitembutton_18': 'songList_mobilelistitembutton_18',
        'mobilelistitem_6': 'songList_mobilelistitem_6',
        'mobilelistitembutton_20': 'songList_mobilelistitembutton_20',
        'mobilelistitem_7': 'songList_mobilelistitem_7',
        'mobilelistitembutton_22': 'songList_mobilelistitembutton_22',
        'mobilelistitem_8': 'songList_mobilelistitem_8',
        'mobilelistitembutton_24': 'songList_mobilelistitembutton_24',
        'mobilelistitem_9': 'songList_mobilelistitem_9',
        'mobilelistitembutton_26': 'songList_mobilelistitembutton_26',
        'mobilelistitem_10': 'songList_mobilelistitem_10',
        'mobilelistitembutton_28': 'songList_mobilelistitembutton_28',
        'mobilelistitem_11': 'songList_mobilelistitem_11',
        'mobilelistitembutton_30': 'songList_mobilelistitembutton_30',
        'mobilelistitem_12': 'songList_mobilelistitem_12',
        'mobilelistitembutton_32': 'songList_mobilelistitembutton_32',
        'mobilelistitem_13': 'songList_mobilelistitem_13',
        'mobilelistitembutton_34': 'songList_mobilelistitembutton_34',
        'mobilelistitem_14': 'songList_mobilelistitem_14',
        'mobilelistitembutton_36': 'songList_mobilelistitembutton_36',
        'mobilelistitem_15': 'songList_mobilelistitem_15',
        'mobilelistitembutton_38': 'songList_mobilelistitembutton_38',
        'mobilelistitem_16': 'songList_mobilelistitem_16',
        'mobilelistitembutton_40': 'songList_mobilelistitembutton_40',
        'mobilelistitem_17': 'songList_mobilelistitem_17',
        'mobilelistitembutton_42': 'songList_mobilelistitembutton_42',
        'mobilelistitem_18': 'songList_mobilelistitem_18',
        'mobilelistitembutton_44': 'songList_mobilelistitembutton_44',
        'mobilelistitem_19': 'songList_mobilelistitem_19',
        'mobilelistitembutton_46': 'songList_mobilelistitembutton_46',
        'mobilelistitem_20': 'songList_mobilelistitem_20',
        'mobilelistitembutton_48': 'songList_mobilelistitembutton_48',
        'mobilelistitem_21': 'songList_mobilelistitem_21',
        'mobilelistitembutton_55': 'songList_mobilelistitembutton_55',
        'mobilelistitem_22': 'songList_mobilelistitem_22',
        'mobilelistitembutton_57': 'songList_mobilelistitembutton_57',
        'mobilelistitem_23': 'songList_mobilelistitem_23',
        'mobilelistitembutton_59': 'songList_mobilelistitembutton_59',
        'mobilelistitem_24': 'songList_mobilelistitem_24',
        'mobilelistitembutton_61': 'songList_mobilelistitembutton_61',
        'mobilelistitem_25': 'songList_mobilelistitem_25',
        'mobilelistitembutton_63': 'songList_mobilelistitembutton_63',
        'mobilelistitem_26': 'songList_mobilelistitem_26',
        'mobilelistitembutton_65': 'songList_mobilelistitembutton_65',
        'mobilelistitem_27': 'songList_mobilelistitem_27',
        'mobilelistitembutton_67': 'songList_mobilelistitembutton_67',
        'mobilelistitem_28': 'songList_mobilelistitem_28',
        'mobilelistitembutton_69': 'songList_mobilelistitembutton_69',
        'mobilelistitem_29': 'songList_mobilelistitem_29',
        'mobilelistitembutton_71': 'songList_mobilelistitembutton_71',
        'mobilelistitem_30': 'songList_mobilelistitem_30',
        'mobilelistitembutton_73': 'songList_mobilelistitembutton_73',
        'mobilelistitem_31': 'songList_mobilelistitem_31',
        'mobilelistitembutton_75': 'songList_mobilelistitembutton_75',
        'mobilelistitem_32': 'songList_mobilelistitem_32',
        'mobilelistitembutton_77': 'songList_mobilelistitembutton_77',
        'mobilelistitem_33': 'songList_mobilelistitem_33',
        'mobilelistitembutton_79': 'songList_mobilelistitembutton_79',
        'mobilelistitem_34': 'songList_mobilelistitem_34',
        'mobilelistitembutton_81': 'songList_mobilelistitembutton_81',
        'mobilelistitem_35': 'songList_mobilelistitem_35',
        'mobilelistitembutton_83': 'songList_mobilelistitembutton_83',
        'mobilelistitem_36': 'songList_mobilelistitem_36',
        'mobilelistitembutton_85': 'songList_mobilelistitembutton_85',
        'mobilelistitem_37': 'songList_mobilelistitem_37',
        'mobilelistitembutton_87': 'songList_mobilelistitembutton_87',
        'mobilelistitem_38': 'songList_mobilelistitem_38',
        'mobilelistitembutton_89': 'songList_mobilelistitembutton_89',
        'mobilelistitem_39': 'songList_mobilelistitem_39',
        'mobilelistitembutton_91': 'songList_mobilelistitembutton_91',
        'mobilelistitem_40': 'songList_mobilelistitem_40',
        'mobilelistitembutton_93': 'songList_mobilelistitembutton_93',
        'mobilelistitem_41': 'songList_mobilelistitem_41',
        'mobilelistitembutton_95': 'songList_mobilelistitembutton_95',
        'mobilelistitem_42': 'songList_mobilelistitem_42',
        'mobilelistitembutton_97': 'songList_mobilelistitembutton_97',
        'mobilelistitem_43': 'songList_mobilelistitem_43',
        'mobilelistitembutton_99': 'songList_mobilelistitembutton_99',
        'mobilelistitem_44': 'songList_mobilelistitem_44',
        'mobilelistitembutton_101': 'songList_mobilelistitembutton_101',
        'mobilelistitem_45': 'songList_mobilelistitem_45',
        'mobilelistitembutton_103': 'songList_mobilelistitembutton_103',
        'mobilelistitem_46': 'songList_mobilelistitem_46',
        'mobilelistitembutton_105': 'songList_mobilelistitembutton_105',
        'mobilelistitem_47': 'songList_mobilelistitem_47',
        'mobilelistitembutton_107': 'songList_mobilelistitembutton_107',
        'mobilelistitem_48': 'songList_mobilelistitem_48',
        'mobilelistitembutton_109': 'songList_mobilelistitembutton_109',
        'mobilelistitem_49': 'songList_mobilelistitem_49',
        'mobilelistitembutton_111': 'songList_mobilelistitembutton_111',
        'mobilelistitem_50': 'songList_mobilelistitem_50',
        'mobilelistitembutton_113': 'songList_mobilelistitembutton_113',
        'mobilelistitem_51': 'songList_mobilelistitem_51',
        'mobilelistitembutton_115': 'songList_mobilelistitembutton_115',
        'mobilelistitem_52': 'songList_mobilelistitem_52',
        'mobilelistitembutton_117': 'songList_mobilelistitembutton_117',
        'mobilelistitem_53': 'songList_mobilelistitem_53',
        'mobilelistitembutton_119': 'songList_mobilelistitembutton_119',
        'mobilelistitem_54': 'songList_mobilelistitem_54',
        'mobilelistitembutton_121': 'songList_mobilelistitembutton_121',
        'mobilelistitem_55': 'songList_mobilelistitem_55',
        'mobilelistitembutton_123': 'songList_mobilelistitembutton_123'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'songList';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var songList_onLoad = function() {
        songList_elementsExtraJS();
        songList_deviceEvents();
        songList_windowEvents();
        songList_elementsEvents();
    };
    // screen window events
    function songList_windowEvents() {
        $('#songList').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function songList_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function songList_elementsExtraJS() {
        // screen (songList) extra code
        /* songs */
        listView = $("#songList_songs");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#songList_songs .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_1 */
        /* mobilelistitem_2 */
        /* mobilelistitem_3 */
        /* mobilelistitem_4 */
        /* mobilelistitem_5 */
        /* mobilelistitem_6 */
        /* mobilelistitem_7 */
        /* mobilelistitem_8 */
        /* mobilelistitem_9 */
        /* mobilelistitem_10 */
        /* mobilelistitem_11 */
        /* mobilelistitem_12 */
        /* mobilelistitem_13 */
        /* mobilelistitem_14 */
        /* mobilelistitem_15 */
        /* mobilelistitem_16 */
        /* mobilelistitem_17 */
        /* mobilelistitem_18 */
        /* mobilelistitem_19 */
        /* mobilelistitem_20 */
        /* mobilelistitem_21 */
        /* mobilelistitem_22 */
        /* mobilelistitem_23 */
        /* mobilelistitem_24 */
        /* mobilelistitem_25 */
        /* mobilelistitem_26 */
        /* mobilelistitem_27 */
        /* mobilelistitem_28 */
        /* mobilelistitem_29 */
        /* mobilelistitem_30 */
        /* mobilelistitem_31 */
        /* mobilelistitem_32 */
        /* mobilelistitem_33 */
        /* mobilelistitem_34 */
        /* mobilelistitem_35 */
        /* mobilelistitem_36 */
        /* mobilelistitem_37 */
        /* mobilelistitem_38 */
        /* mobilelistitem_39 */
        /* mobilelistitem_40 */
        /* mobilelistitem_41 */
        /* mobilelistitem_42 */
        /* mobilelistitem_43 */
        /* mobilelistitem_44 */
        /* mobilelistitem_45 */
        /* mobilelistitem_46 */
        /* mobilelistitem_47 */
        /* mobilelistitem_48 */
        /* mobilelistitem_49 */
        /* mobilelistitem_50 */
        /* mobilelistitem_51 */
        /* mobilelistitem_52 */
        /* mobilelistitem_53 */
        /* mobilelistitem_54 */
        /* mobilelistitem_55 */
    };
    // screen elements handler
    function songList_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_1"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song1', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_1"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song2', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_2"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song3', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_3"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song4', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_4"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song5', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_5"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song6', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_6"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song7', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_7"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song8', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_8"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song9', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_9"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_10"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song10', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_10"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song11', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_11"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_12"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song12', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_12"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_13"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song13', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_13"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_14"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song14', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_14"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_15"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song15', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_15"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_16"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song16', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_16"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song17', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_17"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_18"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song18', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_18"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_19"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song19', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_19"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_20"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song20', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_20"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_21"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song21', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_21"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_22"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song22', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_22"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_23"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song23', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_23"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_24"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song24', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_24"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_25"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song25', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_25"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_26"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song26', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_26"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song27', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_27"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_28"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song28', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_28"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_29"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song29', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_29"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_30"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song30', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_30"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_31"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song31', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_31"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_32"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song32', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_32"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_33"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song33', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_33"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_34"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song34', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_34"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_35"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song35', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_35"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_36"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song36', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_36"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_37"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song37', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_37"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_38"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song38', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_38"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_39"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song39', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_39"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_40"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song40', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_40"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_41"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song41', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_41"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_42"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song42', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_42"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_43"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song43', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_43"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_44"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song44', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_44"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_45"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song45', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_45"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_46"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song46', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_46"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_47"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song47', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_47"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_48"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song48', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_48"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_49"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song49', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_49"]');
		$(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_50"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song50', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_50"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_51"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song51', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_51"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_52"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song52', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_52"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_53"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song53', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_53"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_54"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song54', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_54"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_55"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song55', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_55"]');
    };
    $(document).off("pagebeforeshow", "#songList").on("pagebeforeshow", "#songList", function(event, ui) {
        Apperyio.CurrentScreen = "songList";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    songList_onLoad();
};
$(document).off("pagecreate", "#songList").on("pagecreate", "#songList", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    songList_js();
});