/*
 * JS for songList generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '0c2b18ad-30dc-4103-ae45-9fdf77d705b4';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "song12",
    "location": "song12.html"
}, {
    "name": "song18",
    "location": "song18.html"
}, {
    "name": "song1",
    "location": "song1.html"
}, {
    "name": "song19",
    "location": "song19.html"
}, {
    "name": "song3",
    "location": "song3.html"
}, {
    "name": "song20",
    "location": "song20.html"
}, {
    "name": "song4",
    "location": "song4.html"
}, {
    "name": "songList",
    "location": "songList.html"
}, {
    "name": "song8",
    "location": "song8.html"
}, {
    "name": "song15",
    "location": "song15.html"
}, {
    "name": "song5",
    "location": "song5.html"
}, {
    "name": "song13",
    "location": "song13.html"
}, {
    "name": "song6",
    "location": "song6.html"
}, {
    "name": "song2",
    "location": "song2.html"
}, {
    "name": "song7",
    "location": "song7.html"
}, {
    "name": "song16",
    "location": "song16.html"
}, {
    "name": "song9",
    "location": "song9.html"
}, {
    "name": "song10",
    "location": "song10.html"
}, {
    "name": "song14",
    "location": "song14.html"
}, {
    "name": "song11",
    "location": "song11.html"
}, {
    "name": "song17",
    "location": "song17.html"
}];

function songList_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'songs': 'songList_songs',
        'mobilelistitem_1': 'songList_mobilelistitem_1',
        'mobilelistitembutton_4': 'songList_mobilelistitembutton_4',
        'mobilelistitem_2': 'songList_mobilelistitem_2',
        'mobilelistitembutton_6': 'songList_mobilelistitembutton_6',
        'mobilelistitem_3': 'songList_mobilelistitem_3',
        'mobilelistitembutton_8': 'songList_mobilelistitembutton_8',
        'mobilelistitem_4': 'songList_mobilelistitem_4',
        'mobilelistitembutton_16': 'songList_mobilelistitembutton_16',
        'mobilelistitem_5': 'songList_mobilelistitem_5',
        'mobilelistitembutton_18': 'songList_mobilelistitembutton_18',
        'mobilelistitem_6': 'songList_mobilelistitem_6',
        'mobilelistitembutton_20': 'songList_mobilelistitembutton_20',
        'mobilelistitem_7': 'songList_mobilelistitem_7',
        'mobilelistitembutton_22': 'songList_mobilelistitembutton_22',
        'mobilelistitem_8': 'songList_mobilelistitem_8',
        'mobilelistitembutton_24': 'songList_mobilelistitembutton_24',
        'mobilelistitem_9': 'songList_mobilelistitem_9',
        'mobilelistitembutton_26': 'songList_mobilelistitembutton_26',
        'mobilelistitem_10': 'songList_mobilelistitem_10',
        'mobilelistitembutton_28': 'songList_mobilelistitembutton_28',
        'mobilelistitem_11': 'songList_mobilelistitem_11',
        'mobilelistitembutton_30': 'songList_mobilelistitembutton_30',
        'mobilelistitem_12': 'songList_mobilelistitem_12',
        'mobilelistitembutton_32': 'songList_mobilelistitembutton_32',
        'mobilelistitem_13': 'songList_mobilelistitem_13',
        'mobilelistitembutton_34': 'songList_mobilelistitembutton_34',
        'mobilelistitem_14': 'songList_mobilelistitem_14',
        'mobilelistitembutton_36': 'songList_mobilelistitembutton_36',
        'mobilelistitem_15': 'songList_mobilelistitem_15',
        'mobilelistitembutton_38': 'songList_mobilelistitembutton_38',
        'mobilelistitem_16': 'songList_mobilelistitem_16',
        'mobilelistitembutton_40': 'songList_mobilelistitembutton_40',
        'mobilelistitem_17': 'songList_mobilelistitem_17',
        'mobilelistitembutton_42': 'songList_mobilelistitembutton_42',
        'mobilelistitem_43': 'songList_mobilelistitem_43',
        'mobilelistitembutton_44': 'songList_mobilelistitembutton_44',
        'mobilelistitem_45': 'songList_mobilelistitem_45',
        'mobilelistitembutton_46': 'songList_mobilelistitembutton_46',
        'mobilelistitem_47': 'songList_mobilelistitem_47',
        'mobilelistitembutton_48': 'songList_mobilelistitembutton_48'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'songList';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var songList_onLoad = function() {
        songList_elementsExtraJS();
        songList_deviceEvents();
        songList_windowEvents();
        songList_elementsEvents();
    };
    // screen window events
    function songList_windowEvents() {
        $('#songList').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function songList_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function songList_elementsExtraJS() {
        // screen (songList) extra code
        /* songs */
        listView = $("#songList_songs");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#songList_songs .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_1 */
        /* mobilelistitem_2 */
        /* mobilelistitem_3 */
        /* mobilelistitem_4 */
        /* mobilelistitem_5 */
        /* mobilelistitem_6 */
        /* mobilelistitem_7 */
        /* mobilelistitem_8 */
        /* mobilelistitem_9 */
        /* mobilelistitem_10 */
        /* mobilelistitem_11 */
        /* mobilelistitem_12 */
        /* mobilelistitem_13 */
        /* mobilelistitem_14 */
        /* mobilelistitem_15 */
        /* mobilelistitem_16 */
        /* mobilelistitem_17 */
        /* mobilelistitem_43 */
        /* mobilelistitem_45 */
        /* mobilelistitem_47 */
    };
    // screen elements handler
    function songList_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_1"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song1', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_1"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song2', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_2"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song3', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_3"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song4', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_4"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song5', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_5"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song6', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_6"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song7', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_7"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song8', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_8"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song9', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_9"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_10"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song10', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_10"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song11', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_11"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_12"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song12', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_12"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_13"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song13', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_13"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_14"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song14', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_14"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_15"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song15', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_15"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_16"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song16', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_16"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song17', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_17"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_43"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song18', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_43"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_45"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song19', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_45"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_47"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song20', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_47"]');
    };
    $(document).off("pagebeforeshow", "#songList").on("pagebeforeshow", "#songList", function(event, ui) {
        Apperyio.CurrentScreen = "songList";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    songList_onLoad();
};
$(document).off("pagecreate", "#songList").on("pagecreate", "#songList", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    songList_js();
});