/*
 * JS for startScreen_clone_1 generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '0c2b18ad-30dc-4103-ae45-9fdf77d705b4';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Song6",
    "location": "Song6.html"
}, {
    "name": "Song7",
    "location": "Song7.html"
}, {
    "name": "Song2",
    "location": "Song2.html"
}, {
    "name": "Song8",
    "location": "Song8.html"
}, {
    "name": "BlessTheLord_1",
    "location": "BlessTheLord_1.html"
}, {
    "name": "Song9",
    "location": "Song9.html"
}, {
    "name": "Song10",
    "location": "Song10.html"
}, {
    "name": "Song3",
    "location": "Song3.html"
}, {
    "name": "startScreen_clone_1",
    "location": "startScreen_clone_1.html"
}, {
    "name": "Song4",
    "location": "Song4.html"
}, {
    "name": "Song5",
    "location": "Song5.html"
}];

function startScreen_clone_1_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelist_2': 'startScreen_clone_1_mobilelist_2',
        'mobilelistitem_3': 'startScreen_clone_1_mobilelistitem_3',
        'mobilelistitembutton_4': 'startScreen_clone_1_mobilelistitembutton_4',
        'mobilelistitem_5': 'startScreen_clone_1_mobilelistitem_5',
        'mobilelistitembutton_6': 'startScreen_clone_1_mobilelistitembutton_6',
        'mobilelistitem_7': 'startScreen_clone_1_mobilelistitem_7',
        'mobilelistitembutton_8': 'startScreen_clone_1_mobilelistitembutton_8',
        'mobilelistitem_15': 'startScreen_clone_1_mobilelistitem_15',
        'mobilelistitembutton_16': 'startScreen_clone_1_mobilelistitembutton_16',
        'mobilelistitem_17': 'startScreen_clone_1_mobilelistitem_17',
        'mobilelistitembutton_18': 'startScreen_clone_1_mobilelistitembutton_18',
        'mobilelistitem_19': 'startScreen_clone_1_mobilelistitem_19',
        'mobilelistitembutton_20': 'startScreen_clone_1_mobilelistitembutton_20',
        'mobilelistitem_21': 'startScreen_clone_1_mobilelistitem_21',
        'mobilelistitembutton_22': 'startScreen_clone_1_mobilelistitembutton_22',
        'mobilelistitem_23': 'startScreen_clone_1_mobilelistitem_23',
        'mobilelistitembutton_24': 'startScreen_clone_1_mobilelistitembutton_24',
        'mobilelistitem_25': 'startScreen_clone_1_mobilelistitem_25',
        'mobilelistitembutton_26': 'startScreen_clone_1_mobilelistitembutton_26',
        'mobilelistitem_27': 'startScreen_clone_1_mobilelistitem_27',
        'mobilelistitembutton_28': 'startScreen_clone_1_mobilelistitembutton_28'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'startScreen_clone_1';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var startScreen_clone_1_onLoad = function() {
        startScreen_clone_1_elementsExtraJS();
        startScreen_clone_1_deviceEvents();
        startScreen_clone_1_windowEvents();
        startScreen_clone_1_elementsEvents();
    };
    // screen window events
    function startScreen_clone_1_windowEvents() {
        $('#startScreen_clone_1').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function startScreen_clone_1_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function startScreen_clone_1_elementsExtraJS() {
        // screen (startScreen_clone_1) extra code
        /* mobilelist_2 */
        listView = $("#startScreen_clone_1_mobilelist_2");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_clone_1_mobilelist_2 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_3 */
        /* mobilelistitem_5 */
        /* mobilelistitem_7 */
        /* mobilelistitem_15 */
        /* mobilelistitem_17 */
        /* mobilelistitem_19 */
        /* mobilelistitem_21 */
        /* mobilelistitem_23 */
        /* mobilelistitem_25 */
        /* mobilelistitem_27 */
    };
    // screen elements handler
    function startScreen_clone_1_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('BlessTheLord_1', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_3"]');
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Song2', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_5"]');
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Song3', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_7"]');
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_15"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Song4', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_15"]');
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Song5', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_17"]');
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_19"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Song6', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_19"]');
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_21"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Song7', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_21"]');
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_23"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Song8', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_23"]');
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_25"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Song9', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_25"]');
        $(document).off("click", '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Song10', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_clone_1_mobilecontainer [name="mobilelistitem_27"]');
    };
    $(document).off("pagebeforeshow", "#startScreen_clone_1").on("pagebeforeshow", "#startScreen_clone_1", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen_clone_1";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    startScreen_clone_1_onLoad();
};
$(document).off("pagecreate", "#startScreen_clone_1").on("pagecreate", "#startScreen_clone_1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_clone_1_js();
});